# Installing packages using pip :---]
#  packages are installed globally, so once we instll it, it will be available for all of our python scripts...

"""pip install requests"""
# to instal requests package...

"""pip install -U requests"""
# to upgrade the already installed package to is latest version...we can even install a specific version by specifying it...

"""pip uninstall requests"""
# to uninstall requests package...

"""pip show requests"""
# to get details related to requests package...

